// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type UserInfoResp struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
}

type UserinfoReq struct {
	UserId int64 `json:"userId"`
}
