// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"gin-quickstart/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户信息
				Method:  http.MethodPost,
				Path:    "/user/info",
				Handler: userInfoHandler(serverCtx),
			},
		},
	)
}
